"""Iniciar banco de dados

Revision ID: 59c7cf02112c
Revises: 
Create Date: 2025-10-31 00:08:22.595768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c7cf02112c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_idade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade_min', sa.Integer(), nullable=False),
    sa.Column('idade_max', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('modalidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('utilizadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sobrenome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('perfil', sa.Enum('administrador', 'professor', 'aluno', 'cliente', name='perfilenum'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('dados_administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dados_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('dados_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dados_professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especialidade', sa.Enum('natacao', 'futebol', name='especialidade'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_alteracoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('data_alteracao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('perfil_antigo', sa.String(length=50), nullable=True),
    sa.Column('perfil_novo', sa.String(length=50), nullable=True),
    sa.Column('dados_extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_servico', sa.Enum('matricula', 'mensalidade', 'aluguer_campo', 'hospedagem', 'piscina_balneario', name='tiposervicoenum'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=50), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_treino',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('modalidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modalidade_id'], ['modalidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo_treino_id', sa.Integer(), nullable=False),
    sa.Column('categoria_idade_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_idade_id'], ['categorias_idade.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['dados_professores.id'], ),
    sa.ForeignKeyConstraint(['tipo_treino_id'], ['tipos_treino.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo', name='dia_semana_enum'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['dados_alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['dados_alunos.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['dados_professores.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presencas')
    op.drop_table('inscricoes')
    op.drop_table('horarios')
    op.drop_table('turmas')
    op.drop_table('tipos_treino')
    op.drop_table('pagamentos')
    op.drop_table('historico_alteracoes')
    op.drop_table('dados_professores')
    op.drop_table('dados_clientes')
    op.drop_table('dados_alunos')
    op.drop_table('dados_administradores')
    op.drop_table('utilizadores')
    op.drop_table('modalidades')
    op.drop_table('categorias_idade')
    # ### end Alembic commands ###
